title: Startup Therapy
description: Launch a startup and feel better already!
author: MarcoSantonastasi
remote_theme: StartupTherapy/st_theme_minimal
logo: /assets/img/ST-logo.png
favicon: /assets/img/favicon.ico
show_downloads: false

collections:
  episodes:
    output: true
  
# Instructions for Jekyll SEO plugin sitewide cofiguraiton. https://jekyll.github.io/jekyll-seo-tag
# Post-specific configuration is in the front matter fo the sample document teplate
# lang - The locale these tags are marked up in. Of the format language_TERRITORY. Default is en_US.
# title - Your site's title (e.g., Ben's awesome site, The GitHub Blog, etc.)
# description - A short description (e.g., A blog dedicated to reviewing cat gifs)
# url - The full URL to your site. Note: site.github.url will be used by default.
# author - global author information (see Advanced usage)
# twitter - The following properties are available:
#             twitter:
#               card: - The site's default card type
#               username: - The site's Twitter handle.
#
# facebook - The following properties are available:
#              facebook:
#                app_id: - a Facebook app ID for Facebook insights
#                publisher: - a Facebook page URL or ID of the publishing entity
#                admins: - a Facebook user ID for domain insights linked to a personal account
# logo - URL to a site-wide logo
# social - For specifying social profiles. (complex; read more)
# google_site_verification - for verifying ownership via Google webmaster tools.
# Alternatively, verify ownership with several services at once using the following format:
# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234

# The SEO tag will respect the following YAML front matter if included in a post, page, or document:
# Note: Front matter defaults can be used for any of the above values as described in advanced usage with an image example.
# title - The title of the post, page, or document
# description - A short description of the page's content
# image - URL to an image associated with the post, page, or document (e.g., /assets/page-pic.jpg)
# author - Page-, post-, or document-specific author information (see Advanced usage)
# lang - Page-, post-, or document-specific language information
